[기능] 메인페이지UI 추가
team-joytas/wooco-fe pull request #8
Opened 2024-12-18 09:20 UTC by yoouung

## 📝 개요

- 메인페이지 UI 구현

## ✨ 변경 사항

- 코드나 기능의 주요 변경 사항을 설명합니다.

  - ✨ 메인페이지 UI 구현

## 📸 스크린샷 (옵션)

<img width="378" alt="image" src="https://github.com/user-attachments/assets/8ab9426c-27bd-4371-8a29-cee1aabece18" />

## ℹ️ 참고 사항

TODO:
- 코스 검색 API 연동
- 코스 태그 리스트 수정
- 서비스 소개 이미지 만들기

2024-12-18 09:21 UTC, yoouung commented
메인페이지 내용이 너무 없어서 뭘 더 채워야할 것 같은데.. 아이디어가 없슴다 ... 흑흑

2024-12-18 12:09 UTC, erica0321 requested changes

2024-12-18 12:09 UTC, erica0321 commented on src/app/page.tsx
> +      <div className='flex flex-col text-[10px] w-full mt-[20px] px-[10px] gap-[2px] text-gray-300'>
이 부분은 컴포넌트로 빼놓는게 좋을것 같기도 함니다

2024-12-18 12:09 UTC, erica0321 commented on src/app/page.tsx
> +        <div className='flex flex-wrap gap-4'>
gap-4는 4rem을 의미해서 px단위나 rem단위로 통일하면 좋을듯

2024-12-18 12:09 UTC, erica0321 commented on src/app/regionData.ts
regionData보다 getData로 데이터 받는 파일 이름 통일하는게 좋을듯

2024-12-18 12:09 UTC, erica0321 commented on src/app/_type/courseType.ts
폴더명 _type보다 types가 더 좋을 듯싶슴다

2024-12-18 12:09 UTC, erica0321 commented on src/app/page.tsx
> +              className={`inline-flex items-center justify-center px-5 border border-gray-200 h-[30px] rounded-full text-[12px] cursor-pointer ${
여기도 px 단위로 할건지 rem 단위로 할건지

2024-12-18 12:11 UTC, erica0321 requested changes

2024-12-18 12:11 UTC, erica0321 commented on src/app/page.tsx
> +              className={`inline-flex items-center justify-center px-5 border border-gray-200 h-[30px] rounded-full text-[12px] cursor-pointer ${
카테고리 스타일은 categories / new / page.tsx 에 있는 코드로 대체하면 될듯요

2024-12-19 01:22 UTC, yoouung commented on src/app/_type/courseType.ts
next에서 app 폴더 안에 있는 폴더들 다 라우팅되니까 얘는 프라이빗 폴더로 만들었습니당.. 아니면 types로 하고 app 밖으로 뺄게유
그리고 이거 components도 해당된다고 생각하는데.. 의견 부탁ㅠ

2024-12-19 01:48 UTC, erica0321 commented on src/app/_type/courseType.ts
types는 빼는건 찬성인데 components는 안빼도 될듯 생각됩니답

2024-12-19 01:51 UTC, yoouung commented
### 수정 사항
- 서비스 이용약관/개인정보처리방침 빈 페이지 추가, link href 경로 설정
- types 폴더로 바꾸고 app 밖으로 이동
  - 카테고리 types/Categories.ts 파일에 저장
- 스타일 수정(rem -> px, 카테고리)

2024-12-19 01:52 UTC, yoouung commented on src/app/_type/courseType.ts
오호.... 그렇네여

2024-12-19 01:53 UTC, yoouung commented on src/app/_type/courseType.ts
확인확인

2024-12-20 04:07 UTC, erica0321 approved these changes
굳쟙

2024-12-20 04:08 UTC, merged